# Override file for development
# This file is automatically loaded by docker-compose for local development

services:
  api:
    build:
      target: development

    environment:
      # Override for development
      PYTHONUTF8: 1
      PYTHONUNBUFFERED: 1
      DEBUG: "true"
      DEV_MODE: "true"
    volumes:
      - .:/app  # Mount source code for development
    command: ["uv", "run", "-m", "service.main", "--reload"]

  crawler:
    build:
      target: development
    volumes:
      - .:/app  # Mount source code for development

  # Additional services for development
  adminer:
    image: adminer
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db