# Override file for development
# This file is automatically loaded by docker-compose for local development

services:
  api:
    build:
      context: .
      target: development
    environment:
      # Override for development
      DEBUG: "true"
      DEV_MODE: "true"
    volumes:
      - ./service:/app/service
      - ./data:/app/data
      - ./enrichment:/app/enrichment
      - ./pyproject.toml:/app/pyproject.toml
      - ./uv.lock:/app/uv.lock
    command: ["uv", "run", "-m", "service.main", "--reload"]

  crawler:
    build:
      context: .
      target: development
    environment:
      DEBUG: "true"
      DEV_MODE: "true"
    volumes:
      - ./crawler:/app/crawler
      - ./data:/app/data
      - ./output:/app/output
      - ./pyproject.toml:/app/pyproject.toml
      - ./uv.lock:/app/uv.lock
