# Override file for development
# This file is automatically loaded by docker-compose for local development

services:
  api:
    build:
      context: .
      target: development
    env_file:
      - .env
    environment:
      # Override for development
      DEBUG: "true"
      DEV_MODE: "true"
    volumes:
      - .:/app  # Mount source code for development
    command: ["uv", "run", "-m", "service.main", "--reload"]

  crawler:
    build:
      context: .
      target: development
    env_file:
      - .env
    environment:
      DEBUG: "true"
      DEV_MODE: "true"
    volumes:
      - .:/app  # Mount source code for development
